macos_machine:
  - x86_64-apple-darwin13.4.0
  - arm64-apple-darwin20.0.0
cross_target_platform:
  - osx-64
  - osx-arm64
zip_keys:
  - - cross_target_platform
    - macos_machine
gfortran_version:
  - 7.5.0
  - 9.3.0
  - 10.2.0
  - 11.0.0
