macos_machine:                 # [osx]
  - x86_64-apple-darwin13.4.0  # [osx and x86_64]
  - arm64-apple-darwin20.0.0   # [osx and arm64]
MACOSX_DEPLOYMENT_TARGET:      # [osx]
  - 10.9                       # [osx and x86_64]
  - 11.1                       # [osx and arm64]
macos_min_version:             # [osx]
  - 10.10                      # [osx and x86_64]
  - 11.1                       # [osx and arm64]
CONDA_BUILD_SYSROOT:           # [osx]
  - /opt/MacOSX10.10.sdk       # [osx and x86_64]
  - /Library/Developer/CommandLineTools/SDKs/MacOSX11.1.sdk  # [osx and arm64]
gfortran_version:
  - 11.2.0                     # [osx]
  - 0.0.0                      # [not osx]

