macos_machine:
  - x86_64-apple-darwin13.4.0
  - arm64-apple-darwin20.0.0
cross_target_platform:
  - osx-64
  - osx-arm64
gfortran_version:
  - 13.2.0
  - 12.3.0
libgfortran_version:
  - 5.0.0
  - 5.0.0
zip_keys:
  - - gfortran_version
    - libgfortran_version
  - - cross_target_platform
    - macos_machine
