# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.
# -*- mode: yaml -*-

jobs:
- job: linux
  pool:
    vmImage: ubuntu-latest
  strategy:
    matrix:
      linux_64_cross_target_platformosx-64gfortran_version10.2.1macos_machinex86_64-apple-darwin13.4.0:
        CONFIG: linux_64_cross_target_platformosx-64gfortran_version10.2.1macos_machinex86_64-apple-darwin13.4.0
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-cos7-x86_64
      linux_64_cross_target_platformosx-64gfortran_version10.3.0macos_machinex86_64-apple-darwin13.4.0:
        CONFIG: linux_64_cross_target_platformosx-64gfortran_version10.3.0macos_machinex86_64-apple-darwin13.4.0
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-cos7-x86_64
      linux_64_cross_target_platformosx-64gfortran_version11.0.1macos_machinex86_64-apple-darwin13.4.0:
        CONFIG: linux_64_cross_target_platformosx-64gfortran_version11.0.1macos_machinex86_64-apple-darwin13.4.0
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-cos7-x86_64
      linux_64_cross_target_platformosx-64gfortran_version7.5.0macos_machinex86_64-apple-darwin13.4.0:
        CONFIG: linux_64_cross_target_platformosx-64gfortran_version7.5.0macos_machinex86_64-apple-darwin13.4.0
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-cos7-x86_64
      linux_64_cross_target_platformosx-64gfortran_version9.3.0macos_machinex86_64-apple-darwin13.4.0:
        CONFIG: linux_64_cross_target_platformosx-64gfortran_version9.3.0macos_machinex86_64-apple-darwin13.4.0
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-cos7-x86_64
      linux_64_cross_target_platformosx-arm64gfortran_version10.2.1macos_machinearm64-apple-darwin20.0.0:
        CONFIG: linux_64_cross_target_platformosx-arm64gfortran_version10.2.1macos_machinearm64-apple-darwin20.0.0
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-cos7-x86_64
      linux_64_cross_target_platformosx-arm64gfortran_version10.3.0macos_machinearm64-apple-darwin20.0.0:
        CONFIG: linux_64_cross_target_platformosx-arm64gfortran_version10.3.0macos_machinearm64-apple-darwin20.0.0
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-cos7-x86_64
      linux_64_cross_target_platformosx-arm64gfortran_version11.0.1macos_machinearm64-apple-darwin20.0.0:
        CONFIG: linux_64_cross_target_platformosx-arm64gfortran_version11.0.1macos_machinearm64-apple-darwin20.0.0
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-cos7-x86_64
      linux_64_cross_target_platformosx-arm64gfortran_version7.5.0macos_machinearm64-apple-darwin20.0.0:
        CONFIG: linux_64_cross_target_platformosx-arm64gfortran_version7.5.0macos_machinearm64-apple-darwin20.0.0
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-cos7-x86_64
      linux_64_cross_target_platformosx-arm64gfortran_version9.3.0macos_machinearm64-apple-darwin20.0.0:
        CONFIG: linux_64_cross_target_platformosx-arm64gfortran_version9.3.0macos_machinearm64-apple-darwin20.0.0
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-cos7-x86_64
      linux_aarch64_cross_target_platformosx-64gfortran_version10.2.1macos_machinex86_64-apple-darwin13.4.0:
        CONFIG: linux_aarch64_cross_target_platformosx-64gfortran_version10.2.1macos_machinex86_64-apple-darwin13.4.0
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-aarch64
      linux_aarch64_cross_target_platformosx-64gfortran_version10.3.0macos_machinex86_64-apple-darwin13.4.0:
        CONFIG: linux_aarch64_cross_target_platformosx-64gfortran_version10.3.0macos_machinex86_64-apple-darwin13.4.0
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-aarch64
      linux_aarch64_cross_target_platformosx-64gfortran_version11.0.1macos_machinex86_64-apple-darwin13.4.0:
        CONFIG: linux_aarch64_cross_target_platformosx-64gfortran_version11.0.1macos_machinex86_64-apple-darwin13.4.0
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-aarch64
      linux_aarch64_cross_target_platformosx-64gfortran_version7.5.0macos_machinex86_64-apple-darwin13.4.0:
        CONFIG: linux_aarch64_cross_target_platformosx-64gfortran_version7.5.0macos_machinex86_64-apple-darwin13.4.0
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-aarch64
      linux_aarch64_cross_target_platformosx-64gfortran_version9.3.0macos_machinex86_64-apple-darwin13.4.0:
        CONFIG: linux_aarch64_cross_target_platformosx-64gfortran_version9.3.0macos_machinex86_64-apple-darwin13.4.0
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-aarch64
      linux_aarch64_cross_target_platformosx-arm64gfortran_version10.2.1macos_machinearm64-apple-darwin20.0.0:
        CONFIG: linux_aarch64_cross_target_platformosx-arm64gfortran_version10.2.1macos_machinearm64-apple-darwin20.0.0
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-aarch64
      linux_aarch64_cross_target_platformosx-arm64gfortran_version10.3.0macos_machinearm64-apple-darwin20.0.0:
        CONFIG: linux_aarch64_cross_target_platformosx-arm64gfortran_version10.3.0macos_machinearm64-apple-darwin20.0.0
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-aarch64
      linux_aarch64_cross_target_platformosx-arm64gfortran_version11.0.1macos_machinearm64-apple-darwin20.0.0:
        CONFIG: linux_aarch64_cross_target_platformosx-arm64gfortran_version11.0.1macos_machinearm64-apple-darwin20.0.0
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-aarch64
      linux_aarch64_cross_target_platformosx-arm64gfortran_version7.5.0macos_machinearm64-apple-darwin20.0.0:
        CONFIG: linux_aarch64_cross_target_platformosx-arm64gfortran_version7.5.0macos_machinearm64-apple-darwin20.0.0
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-aarch64
      linux_aarch64_cross_target_platformosx-arm64gfortran_version9.3.0macos_machinearm64-apple-darwin20.0.0:
        CONFIG: linux_aarch64_cross_target_platformosx-arm64gfortran_version9.3.0macos_machinearm64-apple-darwin20.0.0
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-aarch64
      linux_ppc64le_cross_target_platformosx-64gfortran_version10.2.1macos_machinex86_64-apple-darwin13.4.0:
        CONFIG: linux_ppc64le_cross_target_platformosx-64gfortran_version10.2.1macos_machinex86_64-apple-darwin13.4.0
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-ppc64le
      linux_ppc64le_cross_target_platformosx-64gfortran_version10.3.0macos_machinex86_64-apple-darwin13.4.0:
        CONFIG: linux_ppc64le_cross_target_platformosx-64gfortran_version10.3.0macos_machinex86_64-apple-darwin13.4.0
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-ppc64le
      linux_ppc64le_cross_target_platformosx-64gfortran_version11.0.1macos_machinex86_64-apple-darwin13.4.0:
        CONFIG: linux_ppc64le_cross_target_platformosx-64gfortran_version11.0.1macos_machinex86_64-apple-darwin13.4.0
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-ppc64le
      linux_ppc64le_cross_target_platformosx-64gfortran_version7.5.0macos_machinex86_64-apple-darwin13.4.0:
        CONFIG: linux_ppc64le_cross_target_platformosx-64gfortran_version7.5.0macos_machinex86_64-apple-darwin13.4.0
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-ppc64le
      linux_ppc64le_cross_target_platformosx-64gfortran_version9.3.0macos_machinex86_64-apple-darwin13.4.0:
        CONFIG: linux_ppc64le_cross_target_platformosx-64gfortran_version9.3.0macos_machinex86_64-apple-darwin13.4.0
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-ppc64le
      linux_ppc64le_cross_target_platformosx-arm64gfortran_version10.2.1macos_machinearm64-apple-darwin20.0.0:
        CONFIG: linux_ppc64le_cross_target_platformosx-arm64gfortran_version10.2.1macos_machinearm64-apple-darwin20.0.0
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-ppc64le
      linux_ppc64le_cross_target_platformosx-arm64gfortran_version10.3.0macos_machinearm64-apple-darwin20.0.0:
        CONFIG: linux_ppc64le_cross_target_platformosx-arm64gfortran_version10.3.0macos_machinearm64-apple-darwin20.0.0
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-ppc64le
      linux_ppc64le_cross_target_platformosx-arm64gfortran_version11.0.1macos_machinearm64-apple-darwin20.0.0:
        CONFIG: linux_ppc64le_cross_target_platformosx-arm64gfortran_version11.0.1macos_machinearm64-apple-darwin20.0.0
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-ppc64le
      linux_ppc64le_cross_target_platformosx-arm64gfortran_version7.5.0macos_machinearm64-apple-darwin20.0.0:
        CONFIG: linux_ppc64le_cross_target_platformosx-arm64gfortran_version7.5.0macos_machinearm64-apple-darwin20.0.0
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-ppc64le
      linux_ppc64le_cross_target_platformosx-arm64gfortran_version9.3.0macos_machinearm64-apple-darwin20.0.0:
        CONFIG: linux_ppc64le_cross_target_platformosx-arm64gfortran_version9.3.0macos_machinearm64-apple-darwin20.0.0
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-ppc64le
  timeoutInMinutes: 360

  steps:
  - script: |
         rm -rf /opt/ghc
         df -h
    displayName: Manage disk space

  # configure qemu binfmt-misc running.  This allows us to run docker containers
  # embedded qemu-static
  - script: |
      docker run --rm --privileged multiarch/qemu-user-static:register --reset --credential yes
      ls /proc/sys/fs/binfmt_misc/
    condition: not(startsWith(variables['CONFIG'], 'linux_64'))
    displayName: Configure binfmt_misc

  - script: |
        export CI=azure
        export GIT_BRANCH=$BUILD_SOURCEBRANCHNAME
        export FEEDSTOCK_NAME=$(basename ${BUILD_REPOSITORY_NAME})
        if [[ "${BUILD_REASON:-}" == "PullRequest" ]]; then
          export IS_PR_BUILD="True"
        else
          export IS_PR_BUILD="False"
        fi
        .scripts/run_docker_build.sh
    displayName: Run docker build
    env:
      BINSTAR_TOKEN: $(BINSTAR_TOKEN)
      FEEDSTOCK_TOKEN: $(FEEDSTOCK_TOKEN)
      STAGING_BINSTAR_TOKEN: $(STAGING_BINSTAR_TOKEN)